# Generated by Django 3.2.3 on 2021-12-11 22:20

import app.categoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.TextField(default='(122,122,122)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(default='post/infoblog-logo.png', upload_to=app.categoria.models.Categoria.user_directory_path),
        ),
    ]
