# Generated by Django 3.2.3 on 2021-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_auto_20211211_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cuerpo',
            field=models.TextField(default='', max_length=250, verbose_name='Cuerpo'),
        ),
    ]
