# Generated by Django 3.2.3 on 2021-12-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_alter_comentarios_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
