# Generated by Django 3.2.9 on 2021-12-03 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
