# Generated by Django 3.2.9 on 2021-12-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ('fecha_registro',)},
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
