# Generated by Django 3.2.9 on 2021-12-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211203_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
