# Generated by Django 3.2.9 on 2021-12-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacar'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(verbose_name='Cuerpo'),
        ),
    ]
