# Generated by Django 3.2.9 on 2021-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numero_comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='numero_visitas',
            field=models.IntegerField(default=0),
        ),
    ]
