# Generated by Django 3.2.9 on 2021-12-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20211218_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='numero_comentarios',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='numero_visitas',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
