# Generated by Django 3.2.9 on 2021-12-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20211218_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='numero_comentarios',
            field=models.IntegerField(default=0),
        ),
    ]
