# Generated by Django 3.2.9 on 2021-12-20 16:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_numero_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Cuerpo'),
        ),
    ]
